---
title: "SSC 442 Group 8"
author: "Alison Ferer, Clay Herwat, Arie Park, Haoyan Lin"
date: "October 9, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## you may need to change where the data is being pulled from depending on where it is stored on your computer
library(tidyverse)
library(lubridate)
library(ggplot2)
rats_raw <- read_csv("Rat_Sightings.csv", na = c("", "NA", "N/A"))
rats_clean <- rats_raw %>%
     rename(created_date = `Created Date`,
            location_type = `Location Type`,
            borough = Borough) %>%
     mutate(created_date = mdy_hms(created_date)) %>%
     mutate(sighting_year = year(created_date),
            sighting_month = month(created_date),
            sighting_day = day(created_date),
            sighting_weekday = wday(created_date, label = TRUE, abbr = FALSE)) %>%
     filter(borough != "Unspecified")
```

```{r}
 rats_clean %>% 
  group_by(sighting_month, borough, sighting_year) %>% 
  summarize(count=n()) %>%
  ggplot(aes(x=sighting_month, y= count, fill= borough))+ 
  geom_col()+ 
  facet_wrap(vars(sighting_year))
```
```{r}
## animation, install gganimate if you don't have it
library(gganimate)
p + transition_time(sighting_year)+ labs(title = "Year: {round(frame_time,digits=0)}")
```

```{r}
rats_season <- rats_clean %>% mutate(season=ifelse(sighting_month %in% c(12,1,2),"Winter",ifelse(sighting_month %in% c(3,4,5),"Spring",ifelse(sighting_month %in% c(6,7,8),"Summer",ifelse(sighting_month %in% c(9,10,11),"Fall",NA)))))

rats_final <- rats_season %>% filter((sighting_year != 2020 | !(season %in% c("Fall","Winter")))) %>% 
group_by(season,sighting_year,borough) %>% 
summarize(count=n())

rats_final %>% ggplot(aes(x=sighting_year,y=count,color=borough))+
geom_line(size=1)+
facet_wrap(vars(Season=factor(season,levels=c("Winter","Spring","Summer","Fall"))))+
scale_color_manual(name= "Borough", 
labels= c("Bronx","Brooklyn","Manhattan","Queens","Staten Island"),
values=c("#E69F00", "#56B4E9", "#009E73","#F0E442","#0072B2"))+
labs(x="Year",y="Number of Sightings",title="Rat Sightings in NYC over Time by Season and Location Type",fill="Borough")+
scale_x_continuous(breaks=c(2010,2012,2014,2016,2018,2020))+
theme_minimal()
```


```{r}
rats2 <-rats_season %>% 
filter(season=="Spring") %>% 
filter(sighting_year %in% c(2019,2020)) %>% 
mutate(Location=ifelse(location_type %in% c("1-2 Family Dwelling","3+ Family Apt. Building",
"3+ Family Mixed Use Building","1-2 Family Mixed Use Building"),"Residential",
ifelse(location_type %in% c("Commercial Building","Day Care/Nursery","Government Building",
"Office Building","Parking Lot Garage","School/Pre-School"),"Work/School","Other"))) %>% 
group_by(Location,sighting_year) %>% 
summarize(count=n())

ggplot(rats2,aes(x=sighting_year,y=count,fill=factor(Location,levels=c("Work/School","Other","Residential"))))+
geom_col()+
labs(title="Spring 2019-2020 Rat Sighting Breakdown by Location Type",x="Year",y="Number of Sightings",fill="Location")+ 
scale_x_continuous(breaks=c(2019,2020))+
scale_fill_manual(values=c("#0072B2", "#D55E00", "#CC79A7"))
```
